### ISSUE TITLE
Support a file path for the SSH key

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/barnard59-ftp#17]
When used in some GitLab CI pipelines, it can be better to use a file path as argument for the SSH private key instead of the content of the file directly.

This avoids the leak of the private keys in the logs, since only the path will be shown if barnard59 is run in verbose mode.

**Idea of implementation logic:** check the value of `privateKey` option:
- if it's a valid path and if it's pointing to a file that exists
  ⇒ get the content of that file and use it,
- else use the current logic.

Currently, if you try to use a valid path instead of the content of the file, you will get a `Cannot parse privateKey: Unsupported key format` error.

**Comment by cristianvasquez** [comment]
Hi @ludovicm67, I don't have rights to publish a new version!

**Comment by tpluscode** [comment]
That is why we need automation... #19

**Comment by ludovicm67** [comment]
This is available in [v1.0.2](https://github.com/zazuko/barnard59-ftp/releases/tag/v1.0.2).

I'm closing this issue.
